name: CI / Docker Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # ---------- Client ----------
      - name: Install dependencies (client)
        working-directory: ./client
        run: npm install

      - name: Run tests (client)
        working-directory: ./client
        run: |
          if npm run | grep -q "test"; then
            npm test
          else
            echo " No test script found in client, skipping..."
          fi

      # ---------- Backend ----------
      - name: Install dependencies (backend)
        working-directory: ./backend
        run: npm install

      - name: Run tests (backend)
        working-directory: ./backend
        run: |
          if npm run | grep -q "test"; then
            npm test
          else
            echo " No test script found in backend, skipping..."
          fi

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Client build ----------
      - name: Build client
        working-directory: ./client
        run: npm run build || echo " No build script in client"

      # ---------- Backend build ----------
      - name: Build backend (if needed)
        working-directory: ./backend
        run: npm run build || echo " No build script in backend"

  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .
          echo "✅ Docker image built successfully"
          # Future: add docker login + push step if needed

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [test, build, docker]
    steps:
      - name: Notify (placeholder)
        run: echo "🎉 Workflow completed! Tests passed/skipped, build okay, docker image built."
